// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AnnouncerClientProgram;
impl sails_rs::client::Program for AnnouncerClientProgram {}
pub trait AnnouncerClient {
    type Env: sails_rs::client::GearEnv;
    fn announcer(&self) -> sails_rs::client::Service<announcer::AnnouncerImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AnnouncerClient
    for sails_rs::client::Actor<AnnouncerClientProgram, E>
{
    type Env = E;
    fn announcer(&self) -> sails_rs::client::Service<announcer::AnnouncerImpl, Self::Env> {
        self.service(stringify!(Announcer))
    }
}
pub trait AnnouncerClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<AnnouncerClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AnnouncerClientCtors
    for sails_rs::client::Deployment<AnnouncerClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<AnnouncerClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod announcer {
    use super::*;
    pub trait Announcer {
        type Env: sails_rs::client::GearEnv;
        fn announce(
            &mut self,
            announcement: Announcement,
        ) -> sails_rs::client::PendingCall<io::Announce, Self::Env>;
        fn announcements(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Announcements, Self::Env>;
        fn announcements_len(
            &self,
        ) -> sails_rs::client::PendingCall<io::AnnouncementsLen, Self::Env>;
    }
    pub struct AnnouncerImpl;
    impl<E: sails_rs::client::GearEnv> Announcer for sails_rs::client::Service<AnnouncerImpl, E> {
        type Env = E;
        fn announce(
            &mut self,
            announcement: Announcement,
        ) -> sails_rs::client::PendingCall<io::Announce, Self::Env> {
            self.pending_call((announcement,))
        }
        fn announcements(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Announcements, Self::Env> {
            self.pending_call((offset, limit))
        }
        fn announcements_len(
            &self,
        ) -> sails_rs::client::PendingCall<io::AnnouncementsLen, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Announce (announcement: super::Announcement) -> ());
        sails_rs::io_struct_impl!(Announcements (offset: u32, limit: u32) -> Vec<super::Announcement>);
        sails_rs::io_struct_impl!(AnnouncementsLen () -> u32);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AnnouncerEvents {
            Announcement(Announcement),
        }
        impl sails_rs::client::Event for AnnouncerEvents {
            const EVENT_NAMES: &'static [Route] = &["Announcement"];
        }
        impl sails_rs::client::ServiceWithEvents for AnnouncerImpl {
            type Event = AnnouncerEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Announcement {
    pub stealth_address: H160,
    pub caller: H160,
    pub ephemeral_pub_key: Vec<u8>,
    pub metadata: Vec<u8>,
}
