// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RegistryClientProgram;
impl sails_rs::client::Program for RegistryClientProgram {}
pub trait RegistryClient {
    type Env: sails_rs::client::GearEnv;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RegistryClient
    for sails_rs::client::Actor<RegistryClientProgram, E>
{
    type Env = E;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env> {
        self.service(stringify!(Registry))
    }
}
pub trait RegistryClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<RegistryClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RegistryClientCtors
    for sails_rs::client::Deployment<RegistryClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<RegistryClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod registry {
    use super::*;
    pub trait Registry {
        type Env: sails_rs::client::GearEnv;
        fn register_keys(
            &mut self,
            ethereum_address: H160,
            stealth_meta_address: [u8; 66],
        ) -> sails_rs::client::PendingCall<io::RegisterKeys, Self::Env>;
        fn stealth_meta_address_of(
            &self,
            ethereum_address: H160,
        ) -> sails_rs::client::PendingCall<io::StealthMetaAddressOf, Self::Env>;
    }
    pub struct RegistryImpl;
    impl<E: sails_rs::client::GearEnv> Registry for sails_rs::client::Service<RegistryImpl, E> {
        type Env = E;
        fn register_keys(
            &mut self,
            ethereum_address: H160,
            stealth_meta_address: [u8; 66],
        ) -> sails_rs::client::PendingCall<io::RegisterKeys, Self::Env> {
            self.pending_call((ethereum_address, stealth_meta_address))
        }
        fn stealth_meta_address_of(
            &self,
            ethereum_address: H160,
        ) -> sails_rs::client::PendingCall<io::StealthMetaAddressOf, Self::Env> {
            self.pending_call((ethereum_address,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterKeys (ethereum_address: H160, stealth_meta_address: [u8; 66]) -> ());
        sails_rs::io_struct_impl!(StealthMetaAddressOf (ethereum_address: H160) -> Option<[u8; 66]>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum RegistryEvents {
            StealthMetaAddressSet {
                registrant: H160,
                stealth_meta_address: [u8; 66],
            },
        }
        impl sails_rs::client::Event for RegistryEvents {
            const EVENT_NAMES: &'static [Route] = &["StealthMetaAddressSet"];
        }
        impl sails_rs::client::ServiceWithEvents for RegistryImpl {
            type Event = RegistryEvents;
        }
    }
}
