constructor {
  New : ();
};

service Registry {
  RegisterKeys : (ethereum_address: h160, stealth_meta_address: [u8, 66]) -> null;
  query StealthMetaAddressOf : (ethereum_address: h160) -> opt [u8, 66];

  events {
    StealthMetaAddressSet: struct {
      registrant: h160,
      stealth_meta_address: [u8, 66],
    };
  }
};

