type Announcement = struct {
  stealth_address: h160,
  caller: h160,
  ephemeral_pub_key: vec u8,
  metadata: vec u8,
};

constructor {
  New : ();
};

service Announcer {
  Announce : (announcement: Announcement) -> null;
  query Announcements : (offset: u32, limit: u32) -> vec Announcement;

  events {
    Announcement: Announcement;
  }
};

