// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RegistryClientProgram;
impl sails_rs::client::Program for RegistryClientProgram {}
pub trait RegistryClient {
    type Env: sails_rs::client::GearEnv;
    fn redirect(&self) -> sails_rs::client::Service<redirect::RedirectImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RegistryClient
    for sails_rs::client::Actor<RegistryClientProgram, E>
{
    type Env = E;
    fn redirect(&self) -> sails_rs::client::Service<redirect::RedirectImpl, Self::Env> {
        self.service(stringify!(Redirect))
    }
}
pub trait RegistryClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<RegistryClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RegistryClientCtors
    for sails_rs::client::Deployment<RegistryClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<RegistryClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod redirect {
    use super::*;
    pub trait Redirect {
        type Env: sails_rs::client::GearEnv;
        /// TODO: use signature, instead of `eth_address`
        fn register_keys(
            &mut self,
            eth_address: H160,
            stealth_meta_address: [u8; 66],
        ) -> sails_rs::client::PendingCall<io::RegisterKeys, Self::Env>;
    }
    pub struct RedirectImpl;
    impl<E: sails_rs::client::GearEnv> Redirect for sails_rs::client::Service<RedirectImpl, E> {
        type Env = E;
        fn register_keys(
            &mut self,
            eth_address: H160,
            stealth_meta_address: [u8; 66],
        ) -> sails_rs::client::PendingCall<io::RegisterKeys, Self::Env> {
            self.pending_call((eth_address, stealth_meta_address))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterKeys (eth_address: H160, stealth_meta_address: [u8; 66]) -> ());
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum RedirectEvents {
            KeyAdded(H160),
        }
        impl sails_rs::client::Event for RedirectEvents {
            const EVENT_NAMES: &'static [Route] = &["KeyAdded"];
        }
        impl sails_rs::client::ServiceWithEvents for RedirectImpl {
            type Event = RedirectEvents;
        }
    }
}
