/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTokensRouteImport } from './routes/_layout/tokens'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as Layout404RouteImport } from './routes/_layout/404'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutTokensRoute = LayoutTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const Layout404Route = Layout404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/404': typeof Layout404Route
  '/about': typeof LayoutAboutRoute
  '/tokens': typeof LayoutTokensRoute
}
export interface FileRoutesByTo {
  '/404': typeof Layout404Route
  '/about': typeof LayoutAboutRoute
  '/tokens': typeof LayoutTokensRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/404': typeof Layout404Route
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/tokens': typeof LayoutTokensRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/404' | '/about' | '/tokens'
  fileRoutesByTo: FileRoutesByTo
  to: '/404' | '/about' | '/tokens' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/404'
    | '/_layout/about'
    | '/_layout/tokens'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/tokens': {
      id: '/_layout/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof LayoutTokensRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/404': {
      id: '/_layout/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Layout404RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  Layout404Route: typeof Layout404Route
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutTokensRoute: typeof LayoutTokensRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  Layout404Route: Layout404Route,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutTokensRoute: LayoutTokensRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
